# Generated by Django 4.0 on 2021-12-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0002_rename_update_at_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='공개여부'),
        ),
    ]
